apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-minikube
spec:
  selector:
    matchLabels:
      app: hello-minikube
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-minikube
    spec:
      containers:
      - name: hello-minikube
        image: k8s.gcr.io/echoserver:1.10
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-minikube
spec:
  type: LoadBalancer
  selector:
    app: hello-minikube
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
